version: '3.8'

services:
  soil_app:
    container_name: soil_app_container
    image: soil_app_image:latest
    depends_on:
      - db
    build:
      context: .
    ports:
      - 8000:8000
    volumes: 
      - soil_app_data:/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    command: sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   sh entrypoint.sh"
  db:
    container_name: postgres_db_container
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  soil_app_data:
  postgres_data: